package com.topcon.cucumber.definition_steps;

public enum TestKeyword {
    NEW_ADDRESS,
    NEW_ADDRESS_COUNTRY,
    NEW_ADDRESS_TITLE,
    NEW_ADDRESS_FIRST_NAME,
    NEW_ADDRESS_LAST_NAME,
    NEW_ADDRESS_ADDRESS_1,
    NEW_ADDRESS_ADDRESS_2,
    NEW_ADDRESS_TOWN,
    NEW_ADDRESS_POST_CODE,
    NEW_ADDRESS_PHONE,
}
