pipeline {

    parameters {
        choice(choices: 'dev\nqa\nstage\nprod', description: 'Profile name', name: 'Environment')
        choice(choices: ' \n-Dcucumber.options="--tags @SmokeTest --plugin ru.yandex.qatools.allure.cucumberjvm.AllureReporter"', description: 'By default empty. Use param for prod', name: 'Scope')
         }

   agent any
   tools {
       maven 'apache-maven-3.5.4'
   }
   stages {

       stage('mvn compile') {
           steps {
           dir('sarnova-autotests')  {
                 sh "mvn clean test site -Dspring.profiles.active=${params.Environment} ${params.Scope}"
                 }
           }
       }

       stage('generate report') {
           steps {
               allure results: [[path: 'sarnova-autotests/target/allure-results']]
           }
       }
   }
}
