package com.geempower.cucumber.definition_steps;

public enum TestKeyword {
    SHIPPING_ADDRESS,
    CHOSEN_REGION,
    COUNT_OF_PENDING_REQUESTS,
    SELECTED_PRODUCTS,
    CHOSEN_ACCOUNT,
    PO_NO,
    GE_ORDER_NO,
    LA_SHIP_ADDRESS,
    INVOICE_NO,
    REASON_FOR_REQUEST,
    REQUESTED_ACTION,
    COLOR_OF_SHRINK,
    ADDITIONAL_INFO
}