package com.geempower.cucumber.definition_steps;

public enum TestKeyword {
    SHIPPING_ADDRESS,
    CHOSEN_REGION,
    COUNT_OF_PENDING_REQUESTS,
    SELECTED_PRODUCTS,
    CHOSEN_ACCOUNT,
    PO_NO,
    GE_ORDER_NO,
    LA_SHIP_ADDRESS,
    REBATE_END_CUSTOMER_NO,
    REBATE_DISTRIBUTOR_INVOICE_NO,
    REBATE_SPA_NO,
    RETURN_INVOICE_NO,
    RETURN_REASON_FOR_REQUEST,
    RETURN_REQUESTED_ACTION,
    RETURN_COLOR_OF_SHRINK,
    RETURN_ADDITIONAL_INFO,
    RETURN_CATALOG_NO,
    RETURN_REQUEST_CONFIRM_N0,
    MANAGE_USERS_ACCOUNT_NAME
}