package com.sarnova.cucumber.definition_steps;

public enum TestKeyword {
    OPENED_PDP_PRODUCT,
    SELECTED_UOMS_HASH_MAP,
    SUPPLY_LIST_NAME,
    QUICK_ADD_TEXT,
    EDIT_USER_TITLE,
    EDIT_USER_FIRST_NAME,
    EDIT_USER_LAST_NAME,
    EDIT_USER_EMAIL,
    EDIT_USER_USERNAME,
    EDIT_USER_ROLES,
    EDIT_USER_PASSWORD,
    TEST_USER_USERNAME,
    TEST_USER_GROUP_UID,
}
