package com.template.cucumber.definition_steps;

public enum TestKeyword {
    SELECTED_PRODUCTS,
    SHIPPING_ADDRESS,USER_SHIPPING_ADDRESS,
    SHIPPING_ADDRESS_COUNTRY ,SHIPPING_ADDRESS_LINE_1, SHIPPING_ADDRESS_CITY, SHIPPING_ADDRESS_STATE, SHIPPING_ADDRESS_ZIP_CODE, SHIPPING_ADDRESS_TELEPHONE, SHIPPING_ADDRESS_TITLE, SHIPPING_ADDRESS_LINE_2,
    SHIPPING_ADDRESS_FIRST_NAME,
    SHIPPING_ADDRESS_LAST_NAME,
    CREDIT_CARD,USE_SHIPPING_ADDRESS_FOR_BILLING,ORDER,


    NEW_ADDRESS,
    NEW_ADDRESS_COUNTRY,
    NEW_ADDRESS_TITLE,
    NEW_ADDRESS_FIRST_NAME,
    NEW_ADDRESS_LAST_NAME,
    NEW_ADDRESS_ADDRESS_1,
    NEW_ADDRESS_ADDRESS_2,
    NEW_ADDRESS_TOWN,
    NEW_ADDRESS_POST_CODE,
    NEW_ADDRESS_PHONE,;
}
